sonar.projectKey=my-1c-project
sonar.projectName=Мой 1С проект
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.language=bsl
sonar.inclusions=**/*.bsl, **/*.os
sonar.host.url=http://localhost:9000
sonar.bsl.languageserver.skipSupport=with support locked
